name: gh-workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Add a tag.'
        required: false



jobs: 
  my_build: 
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello"
        echo "World"
