name: gh-workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Add a tag.'
        default: ''
        required: false



jobs: 
  my_build: 
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ github.event_name }}
        echo Test ran on ${{ runner.os }} on branch ${{ github.ref }}
