name: gh-workflow

on:
#   push:
#     branches:
#       - master
      
workflow_dispatch:
 tag:
  description: 'Add a tag.'
  required: false

jobs: 
  my_build: 
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello"
        echo "World"
