name: gh-workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Add a tag.'
        default: ''
        required: false
  release:
    types: [created]
    
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ github.event_name }}
        echo Test ran on ${{ runner.os }} on branch ${{ github.ref }}
  
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
